# Generated by Django 5.1.1 on 2024-10-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='email_confirmation_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
