# Generated by Django 5.1.1 on 2024-11-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_enseignant_email_confirmation_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='accepte_cgu',
            field=models.BooleanField(default=False, verbose_name="J'accepte les conditions générales d'utilisation"),
        ),
    ]
