# Generated by Django 5.1.1 on 2024-10-21 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enigme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('a_un_complement_pdf', models.BooleanField(default=False)),
                ('code_partie1', models.CharField(max_length=50)),
                ('code_partie2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('enigmes', models.ManyToManyField(to='enigmes.enigme')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enigmes.classe')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressionEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partie1_resolue', models.BooleanField(default=False)),
                ('partie2_resolue', models.BooleanField(default=False)),
                ('enigme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enigmes.enigme')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enigmes.equipe')),
            ],
            options={
                'unique_together': {('equipe', 'enigme')},
            },
        ),
    ]
