# Generated by Django 5.1.1 on 2024-10-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enigme',
            name='titre_complement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
