# Generated by Django 5.1.1 on 2024-10-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmes', '0002_enigme_titre_complement'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='code_equipe',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
