# Generated by Django 5.1.1 on 2024-10-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmes', '0004_equipe_date_creation_progressionequipe_code_partie1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='nom',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
