# Generated by Django 5.1.1 on 2024-11-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmes', '0005_alter_classe_code_alter_equipe_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='est_active',
            field=models.BooleanField(default=True, help_text='Détermine si les équipes peuvent accéder aux énigmes'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='code_equipe',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
