# Generated by Django 5.1.1 on 2024-11-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmes', '0006_classe_est_active_alter_equipe_code_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
