# Generated by Django 5.1.1 on 2024-11-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmes', '0007_alter_equipe_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='equipe',
            unique_together={('nom', 'classe')},
        ),
    ]
